#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Whos_Home.Resource", IsApplication=true)]

namespace Whos_Home
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int WhosHome = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int buttonConfirm = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int buttonCreateAccount = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int buttonSignIn = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int buttonlogin = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int emailtext = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int passwordtext = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int repeatpasswordtext = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int textCreateAccount = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textOR = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int textconfirmpassword = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int textemail = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int textpassword = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int textusername = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int usernametext = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sign_in = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sign_up = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
