#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Whos_Home.Resource", IsApplication=true)]

namespace Whos_Home
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Couchbase.Lite.Android.Resource.String.library_name = global::Whos_Home.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040013
			public const int aqua = 2130968595;
			
			// aapt resource value: 0x7f040019
			public const int black = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int blue = 2130968599;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_signin_btn_text_dark = 2130968603;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_signin_btn_text_light = 2130968604;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f04001a
			public const int dark_grey = 2130968602;
			
			// aapt resource value: 0x7f04000c
			public const int fuchsia = 2130968588;
			
			// aapt resource value: 0x7f040016
			public const int green = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int grey = 2130968591;
			
			// aapt resource value: 0x7f040014
			public const int lime = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int maroon = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int navy = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int olive = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int purple = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int red = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int silver = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int teal = 2130968597;
			
			// aapt resource value: 0x7f040009
			public const int theme_blue = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int theme_green = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int white = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int yellow = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bills = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blue_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bulletins = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int gray_button = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Lists = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Locations = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int refresh = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int WhosHome = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int WhosHomeIcon = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002b
			public const int BillsCustomAmount = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int BillsCustomBillTitle = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int BillsGraphCategoryTextviewMonth = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int BillsGraphMonthSpinner = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int BillsGraphYearSpinner = 2131296303;
			
			// aapt resource value: 0x7f090039
			public const int BillsNewCheckbox = 2131296313;
			
			// aapt resource value: 0x7f090033
			public const int BillsNewEditText = 2131296307;
			
			// aapt resource value: 0x7f090035
			public const int BillsNewEditTextAmount = 2131296309;
			
			// aapt resource value: 0x7f09003a
			public const int BillsNewListView = 2131296314;
			
			// aapt resource value: 0x7f090044
			public const int BillsNewSpecifyAmountCustomViewEditText = 2131296324;
			
			// aapt resource value: 0x7f090043
			public const int BillsNewSpecifyAmountCustomViewTextView = 2131296323;
			
			// aapt resource value: 0x7f09003f
			public const int BillsNewSpecifyAmountsListView = 2131296319;
			
			// aapt resource value: 0x7f09003e
			public const int BillsNewSpecifyAmountsTextview = 2131296318;
			
			// aapt resource value: 0x7f090037
			public const int BillsNewSpinner = 2131296311;
			
			// aapt resource value: 0x7f090034
			public const int BillsNewTextviewBillAmount = 2131296308;
			
			// aapt resource value: 0x7f090032
			public const int BillsNewTextviewBillName = 2131296306;
			
			// aapt resource value: 0x7f090036
			public const int BillsNewTextviewCategories = 2131296310;
			
			// aapt resource value: 0x7f090038
			public const int BillsNewTextviewSelectUsers = 2131296312;
			
			// aapt resource value: 0x7f09004e
			public const int BulletinCommentText1 = 2131296334;
			
			// aapt resource value: 0x7f09004f
			public const int BulletinCommentText2 = 2131296335;
			
			// aapt resource value: 0x7f090049
			public const int BulletinCommentsListView = 2131296329;
			
			// aapt resource value: 0x7f09007d
			public const int ButtonRefresh = 2131296381;
			
			// aapt resource value: 0x7f09000e
			public const int CancelAddNewLocationButton = 2131296270;
			
			// aapt resource value: 0x7f090052
			public const int GroupText1 = 2131296338;
			
			// aapt resource value: 0x7f090053
			public const int GroupText2 = 2131296339;
			
			// aapt resource value: 0x7f090029
			public const int LocationsLinearLayout = 2131296297;
			
			// aapt resource value: 0x7f09006e
			public const int LocationsLocation = 2131296366;
			
			// aapt resource value: 0x7f09006d
			public const int LocationsUsername = 2131296365;
			
			// aapt resource value: 0x7f09004a
			public const int NewCommentButton = 2131296330;
			
			// aapt resource value: 0x7f090059
			public const int NewGroupButton = 2131296345;
			
			// aapt resource value: 0x7f090065
			public const int NewListButton = 2131296357;
			
			// aapt resource value: 0x7f09005b
			public const int NewListItemButton = 2131296347;
			
			// aapt resource value: 0x7f09006c
			public const int NewLocationButton = 2131296364;
			
			// aapt resource value: 0x7f090073
			public const int NewPostButton = 2131296371;
			
			// aapt resource value: 0x7f090081
			public const int SwitchSettingsMenu = 2131296385;
			
			// aapt resource value: 0x7f090042
			public const int Text = 2131296322;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int buttonAcceptInvite = 2131296266;
			
			// aapt resource value: 0x7f090056
			public const int buttonAddUserToGroup = 2131296342;
			
			// aapt resource value: 0x7f09001a
			public const int buttonBillGraph = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int buttonBillHistory = 2131296279;
			
			// aapt resource value: 0x7f090030
			public const int buttonBillsGraphMonthCancel = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int buttonBillsGraphMonthConfirm = 2131296305;
			
			// aapt resource value: 0x7f09003c
			public const int buttonBillsNewCancel = 2131296316;
			
			// aapt resource value: 0x7f09003d
			public const int buttonBillsNewConfirm = 2131296317;
			
			// aapt resource value: 0x7f09003b
			public const int buttonBillsNewDateSelect = 2131296315;
			
			// aapt resource value: 0x7f090040
			public const int buttonBillsNewSpecifyAmountsCancel = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int buttonBillsNewSpecifyAmountsConfirm = 2131296321;
			
			// aapt resource value: 0x7f090013
			public const int buttonCancelAddUserToGroup = 2131296275;
			
			// aapt resource value: 0x7f090076
			public const int buttonCancelCreateGroup = 2131296374;
			
			// aapt resource value: 0x7f09005f
			public const int buttonCancelListAddItem = 2131296351;
			
			// aapt resource value: 0x7f090063
			public const int buttonCancelListNew = 2131296355;
			
			// aapt resource value: 0x7f090069
			public const int buttonCancelLocationAddName = 2131296361;
			
			// aapt resource value: 0x7f090057
			public const int buttonCancelSelectGroup = 2131296343;
			
			// aapt resource value: 0x7f090094
			public const int buttonConfirm = 2131296404;
			
			// aapt resource value: 0x7f090014
			public const int buttonConfirmAddUserToGroup = 2131296276;
			
			// aapt resource value: 0x7f090060
			public const int buttonConfirmListAddItem = 2131296352;
			
			// aapt resource value: 0x7f090064
			public const int buttonConfirmListNew = 2131296356;
			
			// aapt resource value: 0x7f09006a
			public const int buttonConfirmLocationAddName = 2131296362;
			
			// aapt resource value: 0x7f090072
			public const int buttonCreateAccount = 2131296370;
			
			// aapt resource value: 0x7f09004d
			public const int buttonCreateComment = 2131296333;
			
			// aapt resource value: 0x7f090075
			public const int buttonCreateGroup = 2131296373;
			
			// aapt resource value: 0x7f09007b
			public const int buttonCreateMessage = 2131296379;
			
			// aapt resource value: 0x7f090016
			public const int buttonCurrentBills = 2131296278;
			
			// aapt resource value: 0x7f09000b
			public const int buttonDeclineInvite = 2131296267;
			
			// aapt resource value: 0x7f090018
			public const int buttonNewBill = 2131296280;
			
			// aapt resource value: 0x7f090055
			public const int buttonSelectGroup = 2131296341;
			
			// aapt resource value: 0x7f090070
			public const int buttonSignIn = 2131296368;
			
			// aapt resource value: 0x7f090087
			public const int buttonlogin = 2131296391;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090012
			public const int edittextAddUserToGroupDialog = 2131296274;
			
			// aapt resource value: 0x7f09005e
			public const int edittextListAddItem = 2131296350;
			
			// aapt resource value: 0x7f090062
			public const int edittextListNew = 2131296354;
			
			// aapt resource value: 0x7f090068
			public const int edittextLocationAddName = 2131296360;
			
			// aapt resource value: 0x7f090010
			public const int edittextNewGroup = 2131296272;
			
			// aapt resource value: 0x7f09004c
			public const int edittextcomment = 2131296332;
			
			// aapt resource value: 0x7f09007a
			public const int edittextmessage = 2131296378;
			
			// aapt resource value: 0x7f090078
			public const int edittexttitle = 2131296376;
			
			// aapt resource value: 0x7f090093
			public const int emailtext = 2131296403;
			
			// aapt resource value: 0x7f090089
			public const int firstnametext = 2131296393;
			
			// aapt resource value: 0x7f09001c
			public const int footer = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int footer_border = 2131296283;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f09008b
			public const int lastnametext = 2131296395;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f09005c
			public const int listitemslistview = 2131296348;
			
			// aapt resource value: 0x7f090066
			public const int listlistview = 2131296358;
			
			// aapt resource value: 0x7f090019
			public const int listviewBills = 2131296281;
			
			// aapt resource value: 0x7f09005a
			public const int listviewGroups = 2131296346;
			
			// aapt resource value: 0x7f09000d
			public const int locationlistview = 2131296269;
			
			// aapt resource value: 0x7f090098
			public const int menu_Bills = 2131296408;
			
			// aapt resource value: 0x7f090097
			public const int menu_Lists = 2131296407;
			
			// aapt resource value: 0x7f090095
			public const int menu_Locations = 2131296405;
			
			// aapt resource value: 0x7f090096
			public const int menu_MessageBoard = 2131296406;
			
			// aapt resource value: 0x7f090099
			public const int menu_Space = 2131296409;
			
			// aapt resource value: 0x7f09009a
			public const int menu_notifications = 2131296410;
			
			// aapt resource value: 0x7f09009b
			public const int menu_preferences = 2131296411;
			
			// aapt resource value: 0x7f090074
			public const int messagelistview = 2131296372;
			
			// aapt resource value: 0x7f09007c
			public const int msgText = 2131296380;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f09007e
			public const int notificationslistview = 2131296382;
			
			// aapt resource value: 0x7f09008f
			public const int passwordtext = 2131296399;
			
			// aapt resource value: 0x7f09002c
			public const int plot_view = 2131296300;
			
			// aapt resource value: 0x7f090091
			public const int repeatpasswordtext = 2131296401;
			
			// aapt resource value: 0x7f090086
			public const int signinpassword = 2131296390;
			
			// aapt resource value: 0x7f090084
			public const int signinusername = 2131296388;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f09001d
			public const int tab1 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int tab1_icon = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int tab1_text = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int tab2 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int tab2_icon = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int tab2_text = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int tab3 = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int tab3_icon = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int tab3_text = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int tab4 = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int tab4_icon = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int tab4_text = 2131296296;
			
			// aapt resource value: 0x7f09006f
			public const int textCreateAccount = 2131296367;
			
			// aapt resource value: 0x7f09006b
			public const int textCurrentLocation = 2131296363;
			
			// aapt resource value: 0x7f090071
			public const int textOR = 2131296369;
			
			// aapt resource value: 0x7f09004b
			public const int textcommententer = 2131296331;
			
			// aapt resource value: 0x7f090090
			public const int textconfirmpassword = 2131296400;
			
			// aapt resource value: 0x7f090092
			public const int textemail = 2131296402;
			
			// aapt resource value: 0x7f090088
			public const int textfirstname = 2131296392;
			
			// aapt resource value: 0x7f09008a
			public const int textlastname = 2131296394;
			
			// aapt resource value: 0x7f090079
			public const int textmessage = 2131296377;
			
			// aapt resource value: 0x7f09008e
			public const int textpassword = 2131296398;
			
			// aapt resource value: 0x7f090077
			public const int texttitle = 2131296375;
			
			// aapt resource value: 0x7f09008c
			public const int textusername = 2131296396;
			
			// aapt resource value: 0x7f090009
			public const int textviewAcceptInvite = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int textviewAddLocation = 2131296268;
			
			// aapt resource value: 0x7f090011
			public const int textviewAddUserToGroupDialog = 2131296273;
			
			// aapt resource value: 0x7f090045
			public const int textviewBulletinAuthor = 2131296325;
			
			// aapt resource value: 0x7f090048
			public const int textviewBulletinDate = 2131296328;
			
			// aapt resource value: 0x7f090047
			public const int textviewBulletinMessage = 2131296327;
			
			// aapt resource value: 0x7f090051
			public const int textviewBulletinMessageDialog = 2131296337;
			
			// aapt resource value: 0x7f090046
			public const int textviewBulletinTitle = 2131296326;
			
			// aapt resource value: 0x7f090050
			public const int textviewBulletinTitleDialog = 2131296336;
			
			// aapt resource value: 0x7f090054
			public const int textviewGroupDialog = 2131296340;
			
			// aapt resource value: 0x7f090058
			public const int textviewGroups = 2131296344;
			
			// aapt resource value: 0x7f09005d
			public const int textviewListAddItem = 2131296349;
			
			// aapt resource value: 0x7f090061
			public const int textviewListNew = 2131296353;
			
			// aapt resource value: 0x7f090067
			public const int textviewLocationAddName = 2131296359;
			
			// aapt resource value: 0x7f09000f
			public const int textviewNewGroup = 2131296271;
			
			// aapt resource value: 0x7f090080
			public const int textviewSettingsMenuEmail = 2131296384;
			
			// aapt resource value: 0x7f09007f
			public const int textviewSettingsMenuUsername = 2131296383;
			
			// aapt resource value: 0x7f090082
			public const int textviewSettingsSpace = 2131296386;
			
			// aapt resource value: 0x7f090085
			public const int textviewpassword = 2131296389;
			
			// aapt resource value: 0x7f090083
			public const int textviewusername = 2131296387;
			
			// aapt resource value: 0x7f090015
			public const int toolbar = 2131296277;
			
			// aapt resource value: 0x7f09008d
			public const int usernametext = 2131296397;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AcceptInvite = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddLocation = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddUserToGroup = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddUserToGroupDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Bills = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BillsCustomView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BillsGraph = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BillsGraphMonth = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int BillsNew = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int BillsNewSpecifyAmounts = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int BillsNewSpecifyAmountsCustomView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Bulletin = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int BulletinCommentAdd = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int BulletinCommentCustomView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int BulletinDialog = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int CustomGroupView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int GroupDialog = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Groups = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int List = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ListAddItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ListNew = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Lists = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int LocationAddName = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Locations = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LocationsCustomLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Main = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int MessageBoard = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NewGroup = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int NewMessage = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Notifications = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int SettingsMenu = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int sign_in = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int sign_up = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int toolbar = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int toolbartest = 2130903074;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int edit_menus = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int top_menus = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050013
			public const int ApplicationName = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int Hello = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int library_name = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int url = 2131034132;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ToolBarStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int button_text = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
